In [51]:
import cv2


In [52]:
img = cv2.imread("images/exampleopencv.jpg") # image read
cv2.imshow("wscube tech",img) # image show
cv2.waitKey(0)  # image frame wait time in milisecond and 0 pass keyboard any key press
cv2.destroyAllWindows() # all windows close
#cv2.destroyWindow("wscube tech")  # only one window close


In [53]:

import numpy as np
img = cv2.imread(r"C:\Users\Shubham Anil Birari\OneDrive\Pictures\Images\blizzard.jpeg")
re_image = cv2.resize(img,(500,500)) # resizing images
cv2.imshow("wscubesnow",re_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [54]:
v = np.array([1,2,1,2])
np.hstack((v,v))

array([1, 2, 1, 2, 1, 2, 1, 2])

In [55]:
img = cv2.imread(r"C:\Users\Shubham Anil Birari\OneDrive\Pictures\Images\blizzard.jpeg")
print(img)

[[[112 105 102]
  [108 101  98]
  [101  94  91]
  ...
  [194 185 182]
  [194 185 182]
  [194 185 182]]

 [[109 102  99]
  [106  99  96]
  [100  93  90]
  ...
  [194 185 182]
  [195 186 183]
  [196 187 184]]

 [[110 103 100]
  [106  99  96]
  [100  93  90]
  ...
  [195 186 183]
  [196 187 184]
  [197 188 185]]

 ...

 [[164 155 152]
  [166 157 154]
  [164 155 152]
  ...
  [161 147 149]
  [162 148 150]
  [163 149 151]]

 [[163 154 151]
  [164 155 152]
  [162 153 150]
  ...
  [161 147 149]
  [163 149 151]
  [164 150 152]]

 [[160 151 148]
  [162 153 150]
  [160 151 148]
  ...
  [161 147 149]
  [163 149 151]
  [164 150 152]]]


In [56]:

img = cv2.imread(r"C:\Users\Shubham Anil Birari\OneDrive\Pictures\Images\blizzard.jpeg")
re_image = cv2.resize(img,(400,400)) # resizing images
#h = np.hstack([re_image,re_image]) # horizontal dabule images
#v = np.vstack((re_image,re_image)) # vertical dubule image

h = np.hstack([re_image,re_image]) # multipule dabule images
v = np.vstack((h,h))
cv2.imshow("wscubesnow",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [57]:
import os

list_name = os.listdir(r"C:\Users\Shubham Anil Birari\OneDrive\Pictures\Images")
list_name

['blizzard.jpeg',
 'clear.jpeg',
 'drizzle.jpeg',
 'ice.jpeg',
 'mist.jpeg',
 'overcast.jpeg',
 'rain.jpeg',
 'shower.jpeg',
 'showers.jpeg',
 'side-blur.png',
 'sleet.jpeg',
 'snow.jpeg',
 'sunny.jpeg',
 'thunder.jpeg']

In [58]:
for name in list_name:
    path = "C:\\Users\\Shubham Anil Birari\\OneDrive\\Pictures\\Images"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img,(500,600))
    cv2.imshow("wscube tech", img)
    cv2.waitKey(100)
    cv2.destroyAllWindows()

In [59]:
img_get = cv2.imread("images/exampleopencv.jpg")

# how put text in pic
txt = cv2.putText(img = img_get,
text = "wscube tech",
org = (50,50),
fontFace = cv2.FONT_HERSHEY_SIMPLEX,
fontScale = 3,
color = (255,0,0),
thickness = 2,
lineType = cv2.LINE_8)


cv2.imshow('ws',img_get)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [60]:
#how draw line
old_img = cv2.imread("images/exampleopencv.jpg")
old_img = cv2.resize(old_img,(500,600))


new_img = cv2.line(img= old_img, pt1= (100,60), pt2= (150,100), color = (255,0,0), thickness = 2, lineType= cv2.LINE_8)
cv2.imshow("wscube tech",new_img)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [61]:
#how to draw rectangle
old_img = cv2.imread("images/exampleopencv.jpg")
old_img = cv2.resize(old_img,(500,600))


new_img = cv2.rectangle(img= old_img, pt1= (100,50), pt2= (150,100), color = (255,0,0), thickness = 2, lineType= cv2.LINE_8)

cv2.imshow("wscube tech",new_img)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
#how to draw circle

old_img = cv2.imread("images/exampleopencv.jpg")
old_img = cv2.resize(old_img,(500,600))


new_img = cv2.circle(img= old_img, center= (200,500), radius=50, color = (255,0,0), thickness = 2, lineType= cv2.LINE_8)

cv2.imshow("wscube tech",new_img)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [63]:
# how to draw ellipse
old_img = cv2.imread("images/exampleopencv.jpg")
old_img = cv2.resize(old_img,(500,600))


new_img = cv2.ellipse(img = old_img, center= (300,200), axes=(50,140), angle=45, startAngle= 0, endAngle= 360, color = (255,0,0), thickness = 2, lineType= cv2.LINE_8)
cv2.imshow("wscube tech",new_img)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [64]:
# how to draw polygons


old_img = cv2.imread("images/exampleopencv.jpg")
old_img = cv2.resize(old_img,(500,600))



new_img = cv2.polylines(img= old_img,pts= [np.array([[120,400],[151,300],[300,400],[300,500],[100,500]])] ,isClosed=False, color=(255,0,0), thickness=2, lineType=cv2.LINE_8)


cv2.imshow("wscube tech",new_img)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
#overlapping images
img1 = cv2.imread("images/exampleopencv.jpg")
img2 = cv2.imread("images/exampletimeline.png")

img1 = cv2.resize(img1,(500,500))
img2 = cv2.resize(img2,(500,500))

new_img = cv2.addWeighted(img1,0.5,img2,0.5,0)
#new_img = cv2.subtract(img1,img2)

cv2.imshow("wscube tech",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [66]:
#edes detection of images
img1 = cv2.imread("images/exampleopencv.jpg")
img1 = cv2.resize(img1,(500,500))
print(img1.shape)

new_img = cv2.Canny(img1,100,200)

cv2.imshow("wscube tech",new_img)
cv2.imshow("wscube tech2",img1)

cv2.waitKey(0)
cv2.destroyAllWindows()
#


(500, 500, 3)


In [67]:
#Rotating an image
org_img = cv2.imread("images/exampletimeline.png")
re_image = cv2.resize(org_img,(500,500))
w,h = re_image.shape[0],re_image.shape[1]

m = cv2.getRotationMatrix2D((w/2,h/2),40,1)

new_img = cv2.warpAffine(re_image,m,(h,w))

cv2.imshow("wscube roted",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [69]:
#Image gaussianblur,medianblur bluring


org_img = cv2.imread("images/example4.png")

# Apply blurs to original image
g = cv2.GaussianBlur(org_img, (5, 5), 0)  # Kernel size should be odd
m = cv2.medianBlur(org_img, 5)
b = cv2.bilateralFilter(org_img, 9, 75, 75)

# Resize all to same dimensions
target_size = (200, 200)
res_img = cv2.resize(org_img, target_size)
g = cv2.resize(g, target_size)
m = cv2.resize(m, target_size)
b = cv2.resize(b, target_size)

h = np.hstack((res_img, g, m, b))

cv2.imshow("jav blur", h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [71]:
# img = cv2.imread("images/example5.png")
# re_image = cv2.resize(img,(500,500))
#
# h = np.hstack((re_image,re_image))
# v = np.vstack((h,h))
#
# cv2.imwrite("wscube roted",v) # how to save image
# cv2.waitKey(0)
# cv2.destroyAllWindows()


In [72]:
# how to add boarder in open cv

img = cv2.imread("images/example5.png")
img = cv2.resize(img,(300,300))

img1 = cv2.copyMakeBorder(img, 20,20,20,20,cv2.BORDER_CONSTANT,None,value=2)
img1 = cv2.resize(img1,(300,300))

print(img1.shape)

img2 = cv2.copyMakeBorder(img, 20,20,20,20,cv2.BORDER_DEFAULT,None,value=2)
img2 = cv2.resize(img2,(300,300))

img3 = cv2.copyMakeBorder(img, 20,20,20,20,cv2.BORDER_REFLECT101)
img3 = cv2.resize(img3,(300,300))

img4 = cv2.copyMakeBorder(img, 20,20,20,20,cv2.BORDER_REPLICATE)
img4 = cv2.resize(img4,(300,300))



h = np.hstack((img,img1,img2,img3,img4))

cv2.imshow("wscube tech",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

(300, 300, 3)


In [73]:
# how to run video in opencv
cap = cv2.VideoCapture(r"C:\Users\Shubham Anil Birari\Downloads\opencv video exmaple.mp4")

while cap.isOpened():
    r, frame = cap.read()
    if r == True:
        frame = cv2.resize(frame,(500,500))
        cv2.imshow("wscube tech",frame)
        if cv2.waitKey(25) & 0xFF == ord("q"):
            break
    else:
        break


cap.release()
cv2.destroyAllWindows()

In [74]:
# how to capture webcam in open cv
cap = cv2.VideoCapture(0) # 0 starts webcam
while True:
    r, frame = cap.read()
    if r == True:
        frame = cv2.resize(frame,(500,500))
        cv2.imshow("wscube tech",frame)
        if cv2.waitKey(25) & 0xFF == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

In [75]:
# how to change speed of video in opencv
cap = cv2.VideoCapture(r"C:\Users\Shubham Anil Birari\Downloads\opencv video exmaple.mp4")

while cap.isOpened():
    rat, frame = cap.read()
    frame = cv2.resize(frame,(500,500))
    if rat == True:
        cv2.imshow("wscube tech",frame)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
#image Pyramid pry down
img = cv2.imread("images/example4.png")
print(img.shape)

new = cv2.pyrDown(img)
print(new.shape)

new1 = cv2.pyrDown(new)
print(new1.shape)

new2 = cv2.pyrDown(new1)
print(new2.shape)

cv2.imshow("wscube tech",new)
cv2.imshow("wscube tech1",new1)
cv2.imshow("wscube tech2",new2)
cv2.waitKey(0)
cv2.destroyAllWindows()

(515, 516, 3)
(258, 258, 3)
(129, 129, 3)
(65, 65, 3)


In [ ]:
#image Pyramid pry up
img = cv2.imread("images/example4.png")
print(img.shape)

new = cv2.pyrUp(img)
print(new.shape)

new1 = cv2.pyrUp(new)
print(new1.shape)

new2 = cv2.pyrUp(new1)
print(new2.shape)

cv2.imshow("wscube tech", new)
cv2.imshow("wscube tech1", new1)
cv2.imshow("wscube tech2", new2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#mage Translation using OpenCV
new = cv2.imread("images/example8.png")
new = cv2.resize(new,(500,500))

m = np.float32([[1,0,100],[0,1,50]])

new = cv2.warpAffine(new,m,(500,500))

cv2.imshow("wscube tech",new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#BGR2 colores changing of pictures
org = cv2.imread("images/example7.png")
org = cv2.resize(org,(500,500))

org = cv2.cvtColor(org,cv2.COLOR_BGR2HSV)

cv2.imshow("wscube tech",org)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# croping image

img = cv2.imread("images/example3.png")
img = cv2.resize(img,(500,600))

print(img.shape)

crop = img[120:,:100]

cv2.imshow("wscube tech2",crop)

cv2.imshow("wscube tech",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# how generate blank image
new_img = np.ones((500,500,3),np.uint8)*255 #ones for blank white zeros for blank black
cv2.imshow("wscube tech",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# color Picker using OpenCV Python

def ewz(x):
    pass

img = np.zeros((500,500,3),np.uint8)
cv2.namedWindow("Colour")

cv2.createTrackbar("R", "Colour", 0, 255, ewz)
cv2.createTrackbar("G", "Colour", 0, 255, ewz)
cv2.createTrackbar("B", "Colour", 0, 255, ewz)

while True:
    cv2.imshow("Colour",img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    r = cv2.getTrackbarPos("R", "Colour")
    g = cv2.getTrackbarPos("G", "Colour")
    b = cv2.getTrackbarPos("B", "Colour")

    img[:] = [b,g,r]

cv2.destroyAllWindows()

In [ ]:
# getTrackbarPos() Function in OpenCV
def ewz():
    pass

img = np.zeros((500,500,3),np.uint8)
cv2.namedWindow("bar")
cv2.createTrackbar("on","bar",0,100,ewz)

while True:
    cv2.imshow("bar",img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    var = cv2.getTrackbarPos("on","bar")
    img[:] = [var,0,0]

cv2.destroyAllWindows()

In [ ]:
# how flip & rotate image
img = cv2.imread("images/example5.png")
img = cv2.resize(img,(500,500))

img = cv2.flip(img,1) # y axis flip
img = cv2.flip(img,0) # x axis flip
img = cv2.flip(img,-1) # x&y axis flip

img = cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
img = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISECLOCKWISE)
img = cv2.rotate(img,cv2.ROTATE_180)

img = cv2.transpose(img)


cv2.imshow("wscube tech",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# how to save webcam video in opencv
webcap = cv2.VideoCapture(0)

f = cv2.VideoWriter_fourcc(*"XVID")
out = cv2.VideoWriter('output.avi',f,10,(640,480))

while webcap.isOpened():
    r, frame = webcap.read()
    if r == True:
        frame = cv2.flip(frame,1) # to flip image as webcam video are already flip side
        out.write(frame)
        cv2.imshow("wscube tech",frame)
        if  cv2.waitKey(25) & 0xFF == ord('q'):
            break
    else:
        break

webcap.release()
cv2.destroyAllWindows()

In [ ]:
# how plot histogram on images
import matplotlib.pyplot as plt

In [ ]:
blank_w = np.ones((500,500,3),np.uint8)*255
blank_b = np.zeros((500,500,3),np.uint8)*255

# hist = cv2.calcHist([blank_w],[0],None,[256],[0,256])
hist = cv2.calcHist([blank_b],[0],None,[256],[0,256])


plt.plot(hist)
plt.show()



# cv2.imshow("blank w",blank_w)
cv2.imshow("blank b",blank_b)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
img = cv2.imread("images/example5.png")
b,g,r = cv2.split(img)

hist1 = cv2.calcHist([b],[0],None,[256],[0,256])
hist2 = cv2.calcHist([g],[0],None,[256],[0,256])
hist3 = cv2.calcHist([r],[0],None,[256],[0,256])

plt.subplot(3,1,1)
plt.plot(hist1)

plt.subplot(3,1,2)
plt.plot(hist2)

plt.subplot(3,1,3)
plt.plot(hist3)

plt.show()

cv2.imshow("wscube tech",img)
cv2.imshow("wscube tech1",b)
cv2.imshow("wscube tech2",r)
cv2.imshow("wscube tech3",g)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
img = cv2.imread("images/example5.png")
b,g,r = cv2.split(img)

plt.hist(b.ravel(),255,(0,255),color="blue")
plt.hist(g.ravel(),255,(0,255),color="green")
plt.hist(r.ravel(),255,(0,255),color="red")

plt.show()

In [ ]:

# Read and resize the target image (where you want to find the object)
img = cv2.imread("images/example9.png")
img = cv2.resize(img, (500, 500))
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)  # Convert to HSV (3 channels)

# Read the reference image (the object you want to detect)
img1 = cv2.imread(r"C:\Users\Shubham Anil Birari\OneDrive\Pictures\Screenshots\Screenshot 2026-03-25 120559.png")
hsv2 = cv2.cvtColor(img1, cv2.COLOR_BGR2HSV)  # Convert to HSV (3 channels)

# Create 2D histogram for Hue and Saturation channels [0,1]
# from the reference image (hsv2)
hist = cv2.calcHist([hsv2], [0, 1], None, [180, 256], [0, 180, 0, 256])

# Normalize the histogram
cv2.normalize(hist, hist, 0, 255, cv2.NORM_MINMAX)

# Create back projection on the target image (hsv) using the histogram from reference
mask = cv2.calcBackProject([hsv], [0, 1], hist, [0, 180, 0, 256], 1)

# Apply morphological operations
ker = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, ker)
mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, ker)

# Apply threshold to create binary mask
_, thr = cv2.threshold(mask, 200, 255, cv2.THRESH_BINARY)

# Convert mask to 3-channel for bitwise operations
mask_3channel = cv2.merge([thr, thr, thr])

# Apply mask to original image
res = cv2.bitwise_and(img, mask_3channel)

# Display results
cv2.imshow("Result", res)
cv2.imshow("Original Image", img)
cv2.imshow("Mask", thr)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Displaying  coordinates and color code of the points clicked on the image
def click_b(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        s = f"{x},{y}"
        cv2.putText(img,s,(x,y),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
        cv2.imshow("wscube tech",img)
    elif event == cv2.EVENT_RBUTTONDOWN:
        b = img[y,x,0]
        g = img[y,x,1]
        r = img[y,x,2]
        s = f"{b},{g},{r}"
        cv2.putText(img,s,(x,y),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)
        cv2.imshow("wscube tech",img)




img = cv2.imread("images/example5.png")

cv2.imshow("wscube tech",img)

cv2.setMouseCallback("wscube tech", click_b)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cap = cv2.VideoCapture(r"D:\New folder\pr\shorts\1_05908869adc3bcb78744132052896144_720.mp4")

c = 1
while cap.isOpened():
    r,f = cap.read()
    if r == True:
        file_name = r"D:\New folder\pr\shorts\1_05908869adc3bcb78744132052896144_720.mp4"+str(c)+".jpg"
        c = c+1
        cv2.imshow("wscube tech",f)
        if cv2.waitKey(25) & 0xFF == ord("q"):
            break
        else:
            break

cap.release()
cv2.destroyWindow()